version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgrescdpo
    expose:
    - 5432
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cdpo
    restart: unless-stopped
  cdpo:
    build: .
    network_mode: bridge
    container_name: cdpo
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cdpo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - CDPO_TAGGER_URL=http://tagger:8180
      - CDPO_FOGCATALOGUER_URL=http://fogcataloguer:8280
      - CDPO_SCHEDULE_RATE=600000
      - CDPO_CDPO-COMPOSER_URL=http://cdpo-composer:8010
    restart: unless-stopped
    depends_on:
      - postgrescdpo
    links:
      - postgrescdpo